### ISSUE TITLE
Cassandra regression backend

### ISSUE THREAD

**Issue by gwicke** [gwicke/testreduce#19]
Calculate the regressions and fixes between two commits (change in score), which are identified by timeuuid's. John has done some mock / interface work on this, but implementing this in Cassandra is TODO. Implementation plan to come.

Who: Collin, Pranav
For reference: John's front-end / mock backend work: https://github.com/gwicke/testreduce/pull/14

**Comment by singular-value** [comment]
Collin and I are working on this right now.

**Comment by jjchen** [comment]
I think @choucalate also did some work on this here: https://github.com/gwicke/testreduce/pull/35

**Comment by choucalate** [comment]
Oops! really sorry, I accidentally did this in the front page stats! Feel free to improve it haha

**Comment by singular-value** [comment]
Haha okay, no problem, I'll close this issue for now then and take a look at your code.
