### ISSUE TITLE
Create new article lists with oldid for latest revision

### ISSUE THREAD

**Issue by gwicke** [gwicke/testreduce#25]
The JSON files in articles contain lists of articles for each of a dozen languages. For the new server these should ideally
- also have the oldid of the latest revision of each of these titles
- also have the prefix in the JSON structure, so that we don't need to rely on the file name

An idea is to change the representation of each test to this:

``` javascript
[{prefix: "enwiki", title:"Foo", oldid:556366262}]
```

The oldid for each title can be retrieved with an API query like this:
http://en.wikipedia.org/w/api.php?action=query&prop=revisions&titles=Main%20Page&rvprop=ids&format=json

**Comment by krishnan-chandra** [comment]
My apologies, I actually meant to close this issue and not #27.
